import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>BlogHub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src='/in.js' strategy='lazyOnload'></Script> */}
      <nav className={styles.mainnav}>
        <ul>
          <Link href='/'><a><li>Home</li></a></Link>
          <Link href='/about'><a><li>About</li></a></Link>
          <Link href='/blog'><a><li>Blog</li></a></Link>
          <Link href='/contact'><a><li>Contact</li></a></Link>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
          BlogHub
        </h1>

        <p className={styles.description}>
          Blog Hub By Darklord Powered By JzSoftware 
        </p>

        <Image src="/background.png" width={600} height={500}/>
        {/* <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
        <div className={styles.blog}>
          <h1>Popular Blog</h1>
          <div className="blogcontainer">
            <h3>Maintaining Nextjs App</h3>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rerum commodi labore molestiae, optio tempora laboriosam. Voluptatem soluta vitae ipsum quam repellendus quo repellat ducimus quibusdam! Eos cumque voluptatem natus eius.</p>
          </div>
          <div className="blogcontainer">
            <h3>Maintaining Nextjs App</h3>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rerum commodi labore molestiae, optio tempora laboriosam. Voluptatem soluta vitae ipsum quam repellendus quo repellat ducimus quibusdam! Eos cumque voluptatem natus eius.</p>
          </div>
          <div className="blogcontainer">
            <h3>Maintaining Nextjs App</h3>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rerum commodi labore molestiae, optio tempora laboriosam. Voluptatem soluta vitae ipsum quam repellendus quo repellat ducimus quibusdam! Eos cumque voluptatem natus eius.</p>
          </div><div className="blogcontainer">
            <h3>Maintaining Nextjs App</h3>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rerum commodi labore molestiae, optio tempora laboriosam. Voluptatem soluta vitae ipsum quam repellendus quo repellat ducimus quibusdam! Eos cumque voluptatem natus eius.</p>
          </div><div className="blogcontainer">
            <h3>Maintaining Nextjs App</h3>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rerum commodi labore molestiae, optio tempora laboriosam. Voluptatem soluta vitae ipsum quam repellendus quo repellat ducimus quibusdam! Eos cumque voluptatem natus eius.</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
